apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
  name: magento
spec:
  type: NodePort
  ports:
    - name: port-1
      port: 80
    - name: port-2
      port: 443
  selector:
    app: magento
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
        tier: frontend
    spec:
      containers:
        - image: docker.io/tusharja2986/azure-k8s:#{Build.BuildId}#
          name: magento
          ports:
            - containerPort: 80
            - containerPort: 443
              name: magento

